from enum import StrEnum
from pathlib import PurePosixPath, PureWindowsPath


class FileClassification(StrEnum):
    SOURCE = "source"
    TEST = "test"
    GENERATED = "generated"
    DEPENDENCY_METADATA = "dependency_metadata"
    LOCKFILE = "lockfile"
    BUILD_OUTPUT = "build_output"
    VENDOR = "vendor"
    MINIFIED = "minified"
    DOCUMENTATION = "documentation"
    CONFIGURATION = "configuration"
    UNKNOWN = "unknown"


LOCKFILES = frozenset(
    {
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "npm-shrinkwrap.json",
        "poetry.lock",
        "pipfile.lock",
        "cargo.lock",
        "composer.lock",
        "gemfile.lock",
        "go.sum",
    }
)
BUILD_DIRECTORIES = frozenset({"dist", "build", "out", "coverage", "target", ".next", ".nuxt"})
VENDOR_DIRECTORIES = frozenset({"node_modules", "vendor", ".venv", "venv"})
GENERATED_DIRECTORIES = frozenset({"generated", "__generated__", "gen"})
DEPENDENCY_METADATA = frozenset(
    {"package.json", "pyproject.toml", "requirements.txt", "pom.xml", "go.mod"}
)
SOURCE_LANGUAGES = frozenset({"python", "javascript", "typescript", "java", "html", "css"})
GENERATED_MARKERS = (
    "@generated",
    "code generated",
    "auto-generated",
    "autogenerated",
    "do not edit",
)


def classify_file(
    path_value: str,
    *,
    language: str,
    is_test: bool = False,
    is_documentation: bool = False,
    is_configuration: bool = False,
    is_generated: bool = False,
    content_prefix: str = "",
) -> FileClassification:
    path = PurePosixPath(path_value)
    if (
        not path_value
        or "\\" in path_value
        or path.is_absolute()
        or PureWindowsPath(path_value).is_absolute()
        or ".." in path.parts
    ):
        raise ValueError("path must be repository-relative POSIX form")
    parts = tuple(part.casefold() for part in path.parts)
    directories = frozenset(parts[:-1])
    name = parts[-1]
    if is_generated:
        return FileClassification.GENERATED
    if directories & VENDOR_DIRECTORIES:
        return FileClassification.VENDOR
    if directories & BUILD_DIRECTORIES:
        return FileClassification.BUILD_OUTPUT
    if directories & GENERATED_DIRECTORIES:
        return FileClassification.GENERATED
    if name in LOCKFILES:
        return FileClassification.LOCKFILE
    if name.endswith((".min.js", ".min.css", ".map")):
        return FileClassification.MINIFIED
    prefix = content_prefix[:2048].casefold()
    if any(marker in prefix for marker in GENERATED_MARKERS):
        return FileClassification.GENERATED
    if name in DEPENDENCY_METADATA:
        return FileClassification.DEPENDENCY_METADATA
    if is_test:
        return FileClassification.TEST
    if is_documentation:
        return FileClassification.DOCUMENTATION
    if is_configuration:
        return FileClassification.CONFIGURATION
    if language in SOURCE_LANGUAGES:
        return FileClassification.SOURCE
    return FileClassification.UNKNOWN


EXCLUDED_FINDINGS_CLASSIFICATIONS = frozenset(
    {
        FileClassification.GENERATED,
        FileClassification.LOCKFILE,
        FileClassification.BUILD_OUTPUT,
        FileClassification.VENDOR,
        FileClassification.MINIFIED,
    }
)
